### ISSUE TITLE
hello, I deployed the code to a Linux server, there is a problem "CompVis/stable-diffusion-v1-4 does not appear to have a file named model_index.json.", I want to know how to  solve this problem, or this can only run in MAC or WINDOWS?

### ISSUE THREAD

**Issue by upcJack** [HongyangDu/DistributedDiffusion#1]
![image](https://github.com/HongyangDu/DistributedDiffusion/assets/77914143/3b81698d-31c1-43f5-b37b-5db76e1d90cd)

**Comment by HongyangDu** [comment]
The error message indicates that the local cache does not contain the required model_index.json file, and it also failed to download it from the Hugging Face model hub, likely due to the connectivity problem (The first part of the error indicates a failure to establish a connection, possibly due to network issues. Could you verify that the server has proper internet access and that there are no firewalls or network policies preventing the server from reaching the Hugging Face model hub?)

If the server is indeed connected to the internet and there are no firewalls blocking the connection, could you try manually download the model_index.json file from the model's repository and place it in the expected directory?

Thanks

**Comment by upcJack** [comment]
Thanks, I download the model's repository to my server, but I don't know where is  the expected directory? Could you tell me your overall directory structure? thanks

**Comment by HongyangDu** [comment]
![Uploading 1.png…]()

**Comment by HongyangDu** [comment]
![1](https://github.com/HongyangDu/DistributedDiffusion/assets/53124436/6ddf5877-02a0-4f7a-9428-57bc954d8f91)

**Comment by upcJack** [comment]
Thanks，I solved this problem. Thank you and best wishes!

**Comment by HongyangDu** [comment]
Happy to hear that ^_^ 

For more technical details, please check our latest journal paper "[User-Centric Interactive AI for Distributed Diffusion Model-based AI-Generated Content](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=QI3vo-YAAAAJ&sortby=pubdate&citation_for_view=QI3vo-YAAAAJ:dfsIfKJdRG4C)" https://arxiv.org/abs/2311.11094

Good luck with your research!
